#!/bin/bash
# Auto-delete unused images from GitHub repository
# This script will remove all 186 unused image files

set -e  # Exit on error

echo "Starting automatic image deletion..."
echo "Removing 186 unused files (~208 MB)..."
echo ""

# List of all files to delete
FILES_TO_DELETE=(
  # Category 1: Duplicate PNG files (9)
  "images/16LDualInvertorDehumidifier.png"
  "images/AeroBooster.png"
  "images/AeroFuniture.png"
  "images/AeroHitAirPurifier.png"
  "images/DishwasherQuadWash (2).png"
  "images/DualCoolWithPurifier1.5HP.png"
  "images/HitAirPurifier.png"
  "images/WashMachine AIDD20KW.png"
  "images/WashingMachineDual20KG.png"
  
  # Category 2: Large flyer images (15)
  "images/flyer_page1.png"
  "images/flyer_page2.png"
  "images/flyer_page3.png"
  "images/flyer_page4.png"
  "images/flyer_page5.png"
  "images/flyer_page6.png"
  "images/flyer_page7.png"
  "images/flyer_page8.png"
  "images/flyer_page9.png"
  "images/flyer_page11.png"
  "images/flyer_page16.png"
  "images/flyer_page21.png"
  "images/flyer_page26.png"
  "images/flyer_page31.png"
  "images/flyer_page36.png"
  
  # Category 3: AC numbered sequences (23)
  "images/ac1.jpg"
  "images/ac2.jpg"
  "images/ac3.jpg"
  "images/ac4.jpg"
  "images/ac5.jpg"
  "images/ac6.jpg"
  "images/ac7.jpg"
  "images/ac8.jpg"
  "images/ac9.jpg"
  "images/ac_scene_1.jpg"
  "images/ac_scene_2.jpg"
  "images/aca1.jpg"
  "images/aca2.jpg"
  "images/aca3.jpg"
  "images/aca4.jpg"
  "images/acav1.mp4"
  "images/acav2.mp4"
  "images/acav3.mp4"
  "images/acav4.mp4"
  "images/acv1.mp4"
  "images/acv2.webm"
  "images/acv3.mp4"
  "images/acv4.mp4"
  
  # Category 4: Water purifier sequences (42)
  "images/wpa1.jpg"
  "images/wpa2.jpg"
  "images/wpa3.jpg"
  "images/wpa4.jpg"
  "images/wpa5.jpg"
  "images/wpa6.png"
  "images/wpa7.jpg"
  "images/wpa8.jpg"
  "images/wpa9.jpg"
  "images/wpa10.jpg"
  "images/wpa11.jpg"
  "images/wpa12.jpg"
  "images/wpa13.jpg"
  "images/wpa14.jpg"
  "images/wpa15.jpg"
  "images/wpa16.jpg"
  "images/wpa17.jpg"
  "images/wpa18.jpg"
  "images/wpav2.mp4"
  "images/wpav3.mp4"
  "images/wpb1.mp4"
  "images/wpb2.webm"
  "images/wpb3.webm"
  "images/wpb4.webm"
  "images/wpb5.webm"
  "images/wpb6.jpg"
  "images/wpb7.jpg"
  "images/wpb8.jpg"
  "images/wpb9.jpg"
  "images/wpc1.jpg"
  "images/wpc2.jpg"
  "images/wpc3.jpg"
  "images/wpc4.jpg"
  "images/wpc5.jpg"
  "images/wpc6.jpg"
  "images/wpc7.jpg"
  "images/wpcv1.mp4"
  "images/wpcv2.mp4"
  "images/wpcv3.webm"
  "images/wpcv4.webm"
  "images/wpcv5.webm"
  "images/wpcv6.webm"
  
  # Category 5: Dishwasher sequences (22)
  "images/quadwash-1.jpg"
  "images/quadwash-2.jpg"
  "images/quadwash-3.jpg"
  "images/quadwash-4.jpg"
  "images/quadwash-5.jpg"
  "images/quadwash-6.jpg"
  "images/quadwash-7.jpg"
  "images/quadwash-8.jpg"
  "images/quadwash-9.jpg"
  "images/quadwash-10.jpg"
  "images/quadwash-11.jpg"
  "images/dishwasher-silver-1.jpg"
  "images/dishwasher-silver-2.jpg"
  "images/dishwasher-silver-3.jpg"
  "images/dishwasher-silver-4.jpg"
  "images/dishwasher-silver-5.jpg"
  "images/dishwasher-silver-6.jpg"
  "images/dishwasher-silver-7.jpg"
  "images/dishwasher-silver-8.jpg"
  "images/dishwasher-silver-9.jpg"
  "images/dishwasher-silver-10.jpg"
  "images/dishwasher-silver-11.jpg"
  
  # Category 6: Washing machine sequences (17)
  "images/washt1.jpg"
  "images/washt3.jpg"
  "images/washt4.jpg"
  "images/washt5.webm"
  "images/washt6.jpg"
  "images/washt7.jpg"
  "images/washt8.png"
  "images/washt9.mp4"
  "images/washt10.png"
  "images/washt11.webm"
  "images/washt12.webm"
  "images/washt13.webm"
  "images/washt14.webm"
  "images/washt15.webm"
  "images/washt16.jpg"
  "images/washt17.jpg"
  "images/washt18.jpg"
  
  # Category 7: Washing tower sequences (4)
  "images/washtower-1.jpg"
  "images/washtower-2.jpg"
  "images/washtower-3.jpg"
  "images/washtower2520-1.jpg"
  
  # Category 8: Duplicate detail images (50+)
  "images/aidd-1.jpg"
  "images/aidd-2.jpg"
  "images/aidd-3.jpg"
  "images/aidd10kg-1.jpg"
  "images/aidd10kg-2.jpg"
  "images/aidd10kg-3.jpg"
  "images/aidd10kg-4.jpg"
  "images/aidd15kg-1.jpg"
  "images/aidd15kg-2.jpg"
  "images/aidd15kg-3.jpg"
  "images/aidd15kg-4.jpg"
  "images/aidd20kg-1.jpg"
  "images/aidd20kg-2.jpg"
  "images/aidd20kg-3.jpg"
  "images/aidd20kg-4.jpg"
  "images/aidd105kg-1.jpg"
  "images/aidd105kg-2.jpg"
  "images/aidd105kg-3.jpg"
  "images/aerobooster-1.jpg"
  "images/aerobooster-2.jpg"
  "images/aerofurniture-white-detail.jpg"
  "images/aerofurniture-white.jpg"
  "images/aerofurniture-1.jpg"
  "images/aerofurniture-2.jpg"
  "images/alphapet-double-1.jpg"
  "images/alphapet-double-2.jpg"
  "images/alphapet-double-3.jpg"
  "images/alphapet-single-1.jpg"
  "images/alphapet-single-2.jpg"
  "images/cattower-1.jpg"
  "images/cattower-2.jpg"
  "images/cordzero-1.jpg"
  "images/cordzero-2.jpg"
  "images/cordzero-3.jpg"
  "images/cordzero-4.jpg"
  "images/cordzero-5.jpg"
  "images/dd16gm-1.jpg"
  "images/dd16gm-2.jpg"
  "images/dryer9kg-1.jpg"
  "images/dryer9kg-2.jpg"
  "images/dryer9kg-3.jpg"
  "images/dryer9kg-4.jpg"
  "images/hit-as60-beige-top.jpg"
  "images/hit-as60-white-top.jpg"
  "images/hit-as60-1.jpg"
  "images/hit-as60-2.jpg"
  "images/hit-as65-1.jpg"
  "images/hit-as65-2.jpg"
  "images/hit-as65-3.jpg"
  "images/hit-detail-1.jpg"
  "images/hit-detail-2.jpg"
  "images/hit-detail-3.jpg"
  "images/hit-detail-4.jpg"
  
  # Category 9: Scene/lifestyle images (12)
  "images/air_scene_1.jpg"
  "images/air_scene_2.jpg"
  "images/fridge_scene_1.jpg"
  "images/fridge_scene_2.jpg"
  "images/others_scene_1.jpg"
  "images/others_scene_2.jpg"
  "images/tv_scene_1.jpg"
  "images/tv_scene_2.jpg"
  "images/washer_scene_1.jpg"
  "images/washer_scene_2.jpg"
  "images/water_scene_1.jpg"
  "images/water_scene_2.jpg"
  
  # Category 10: Miscellaneous files (35)
  "images/3water1.jpg"
  "images/3water2.jpg"
  "images/3water3.jpg"
  "images/3water4.jpg"
  "images/3water5.jpg"
  "images/3water6.jpg"
  "images/3water7.jpg"
  "images/3water8.jpg"
  "images/3water9.jpg"
  "images/3water10.jpg"
  "images/3water11.jpg"
  "images/2water2.jpg"
  "images/2water4.jpg"
  "images/2water5.png"
  "images/2water6.jpg"
  "images/2water7.jpg"
  "images/2water8.jpg"
  "images/3waterv1.webm"
  "images/3waterv2.webm"
  "images/3waterv3.webm"
  "images/3waterv4.webm"
  "images/3waterv5.webm"
  "images/3waterv6.webm"
  "images/3waterv7.webm"
  "images/3waterv8.webm"
  "images/heropage.MOV"
  "images/0509.mp4"
  "images/10f16817-9cec-4582-8741-7f86f2c42dcc.jpeg"
  "images/765d0c67-2a64-455d-8832-dc8fc831bfc8.jpeg"
  "images/8652b39d-2c00-4164-bb45-04c125e731e6.jpeg"
  "images/aefe7d95-8cfe-40a1-a63f-2577c1e1b673.jpeg"
  "images/b3d694f5-c24e-480c-b3a9-ad04a92c695e.jpeg"
  "images/IMG_0914.webp"
)

# Count deleted files
count=0

# Delete each file using git
for file in "${FILES_TO_DELETE[@]}"; do
  if git ls-files --error-unmatch "$file" 2>/dev/null; then
    git rm --force "$file" 2>/dev/null
    count=$((count + 1))
    echo "✓ Removed: $file"
  fi
done

echo ""
echo "=========================================="
echo "✓ Cleanup Complete!"
echo "✓ Total files removed: $count"
echo "✓ Space freed: ~208 MB"
echo "=========================================="
echo ""
echo "Next steps:"
echo "1. Review changes: git status"
echo "2. Commit changes: git commit -m 'Remove unused and duplicate images - Free 208 MB storage'"
echo "3. Push to GitHub: git push origin main"
